name: wifi_connector_example
description: Demonstrates how to use the wifi_connector plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  wifi_connector:
    path: ../

flutter:
  uses-material-design: true
